### ISSUE TITLE
Ventas y facturacion-Generar Factura

### ISSUE THREAD

**Issue by sandramendez** [fwilchel/gip3#11]
en el formulario la cantidad de la venta directa se visualiza la misma de la remision. este caso esta muy raro. la venta directa en el sku al consultar tenia 50 cuando se carga la rm en el plano coloque 45, cuando consulto para generar la factura el sku se encuentra en cantidad RM  y cantidad VD 45. realice el ejercicio con otro VD diferente , al inicio tenia 96 al final RM Y VD resulto con 90 en cantidad

**Comment by d5a9p6s7** [comment]
Solucionado en desarrollo.
Requiere despliegue.
