### ISSUE TITLE
Comercio Exterior Reporte - Reimpresioon  Factura Exportacion - los campos en el formulario se alinean a la izq

### ISSUE THREAD

**Issue by jherediab** [fwilchel/gip3#27]
Reimpresion  FX los campos en el formulario se alinean a la izq

**Comment by d5a9p6s7** [comment]
Devolví la versión de la librería de primefaces a la v5.1, compile el reporte e hice pruebas y el problema se sigue presentando.

**Comment by d5a9p6s7** [comment]
Al parecer el problema tiene que ver con el SO donde se compile el reporte, en mi linux sigue generando el error, mientras que en el windows de la maquina de Jhon, funciono bien.
Solucionado en desarrollo.
Requiere despliegue.
