### ISSUE TITLE
Comercio exterior- ingresar solicitud de pedido

### ISSUE THREAD

**Issue by sandramendez** [fwilchel/gip3#34]
esta habilitando el botón de generar solicitud de pedido cuando no hay porducto por cliente
![ingresarsolicitudpedido](https://cloud.githubusercontent.com/assets/12647386/7959774/8b8e8c0c-09c1-11e5-8998-1e400bc9144f.png)

**Comment by d5a9p6s7** [comment]
Solucionado en desarrollo.
Requiere despliegue.
Pruebas locales exitosas
![screenshot from 2015-06-04 11 14 53](https://cloud.githubusercontent.com/assets/1828021/7988813/fc266ca2-0aaa-11e5-9346-24c7ee01b586.png)

**Comment by d5a9p6s7** [comment]
Solucionado en desarrollo.
Requiere despliegue.
Pruebas locales exitosas.
