### ISSUE TITLE
Comercio exterior-menú- ordenar 

### ISSUE THREAD

**Issue by sandramendez** [fwilchel/gip3#37]
1.  Solicitud pedido
2. Asignar lote OIC
3. Costo logistico
4. Ingresar costo incoterm
los demas debe quedar igual

**Comment by d5a9p6s7** [comment]
Se debe ejecutar el script [44. menu comercio nacional orden.sql]
Solucionado en desarrollo.
No requiere despliegue.
![screenshot from 2015-06-04 11 41 23](https://cloud.githubusercontent.com/assets/1828021/7989373/ace0352a-0aae-11e5-97dd-970bb7f85c9f.png)
