### ISSUE TITLE
Comercio exterior-ingresar solicitud pedido-error al cargar archivo

### ISSUE THREAD

**Issue by sandramendez** [fwilchel/gip3#38]
erroreaused by: org.hibernate.exception.SQLGrammarException: ERROR: no existe la columna productosi0_.unidad_min_despacho_x_tendido
  Position: 654
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:122) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
	at or

**Comment by d5a9p6s7** [comment]
Se debe ejecutar el script [42. productos_inventario add column unidad_min_despacho_x_tendido].
Solucionado en desarrollo.
No requiere despliegue.
