### ISSUE TITLE
Maestro-Cliente-no guarda todo los cambios

### ISSUE THREAD

**Issue by sandramendez** [fwilchel/gip3#4]
no guarda el valor en la tabla  log_auditoria en los campos valor_anterior ,valor_nuevo de

**Comment by d5a9p6s7** [comment]
cuando se creen o editen registros sobre la tabla "clientes", es necesario crear un registro por cada uno de los campos modificados en la tabla "log_auditoria".

**Comment by d5a9p6s7** [comment]
Se requiere ejecutar script numero 45.
