### ISSUE TITLE
Comercio Exterior Reporte - Imprimir Factura Exportacion

### ISSUE THREAD

**Issue by jherediab** [fwilchel/gip3#40]
si el documento FX se encuentra en estado "anulado" la impresion pdf debe generar el mensaje "ANULADO". adjunto imagen de muestra

![image](https://cloud.githubusercontent.com/assets/10456852/7989393/d7104b5a-0aae-11e5-8805-9c8002b205f6.png)

**Comment by d5a9p6s7** [comment]
Solucionada en desarrollo.
Requiere despliegue.

**Comment by d5a9p6s7** [comment]
Problema de lazyload

**Comment by d5a9p6s7** [comment]
En ambiente de desarrollo no se presenta.
Probar en ambiente de QA

**Comment by sandramendez** [comment]
funciona correctamente
