### ISSUE TITLE
comercio exterio reportes-consulta solicitud pedido

### ISSUE THREAD

**Issue by sandramendez** [fwilchel/gip3#42]
Esta mostrando unos datos null
![consultasolicitudpedido](https://cloud.githubusercontent.com/assets/12647386/7995217/b711ad32-0ad9-11e5-8d32-b02a7fb71b97.png)

**Comment by sandramendez** [comment]
es problema que no guarda en la tablas cuando se guarda la solicitud de pedido

**Comment by jherediab** [comment]
se modifica aplicacion  SolicitudPedidoMB  guardarAjustesSP para q guarde los datos del formulario

contenedor20 ,contenedor40 y lugar Incoterm 

se verifica reporte xls
