### ISSUE TITLE
Comercio Exterior - Ingresar Solicitud Pedido

### ISSUE THREAD

**Issue by jherediab** [fwilchel/gip3#46]
Al cargar una solicitud de pedido desde un archivo plano con 29 productos, genera error
pero si crea la solicitud, no sale el mensaje del consecutivo q se genero.

adjunto archivo plano.
se envio por correo el archivo de pruebas
PEDIDO_PRUEBA_Corporación  JV de Centroamerica S.A. de C.V. -SP1-1047.txt

**Comment by d5a9p6s7** [comment]
Solucionado en desarrollo.
Requiere despliegue.
