### ISSUE TITLE
comercio nacional-costos logistico-etiquetas resta al valor de cada item y solo deberia sumar al total fob

### ISSUE THREAD

**Issue by sandramendez** [fwilchel/gip3#48]
![sietiqeuta](https://cloud.githubusercontent.com/assets/12647386/8141098/f89e7d1c-1127-11e5-9543-903ebe965963.png)
![menoscostos](https://cloud.githubusercontent.com/assets/12647386/8141102/010d9730-1128-11e5-92ee-4d1a557613e1.png)

**Comment by fwilchel** [comment]
No deberían estar parametrizados como base fob los siguientes
Seguro de mercancia y seguro de transporte 0,091% sobre valor FOB
Imprevistos calculados sobre 10% Valor FOB
Agenciamiento aduanero (0,32% sobre Valor FOB)
Si arreglan esos datos
Creo que ya quedaron Costos Logisticos al pelo
Agregué un chulito en la liquidación de costos logísticos para poder ver cuales items son base FOB
Debes tener en cuenta y hacerle ver a Lorena
 * El valor FOB del final toma todos los items seleccionados cuya categoria sume en valor fob
 * Los items cuyo valor es un % sobre el valor fob, solo toma los items seleccionados con baseFOB
 * Al momento de generar no se tienen en cuenta las etiquetas para distribuir en las solicitudes costos 
 * Al momento de guardar la distribucion de costos si tiene en cuenta las etiquetas

**Comment by sandramendez** [comment]
esta modificando unos decimales cuando la eqtiqueta es  de 100
el inicial era 4826,47
mas 100 etiqueta esta dando 4926,58

**Comment by sandramendez** [comment]
solucionado
