### ISSUE TITLE
comercio nacional-al escribir la cantidad directamente campo y no por flechas genera este error

### ISSUE THREAD

**Issue by sandramendez** [fwilchel/gip3#52]
![editael campo manual no flechas](https://cloud.githubusercontent.com/assets/12647386/8141897/23a97c80-1134-11e5-8fe8-10af4b36db9c.png)

**Comment by d5a9p6s7** [comment]
ese es el comportamiento deseado, solo permite cambiar por valores multiplos de la unidad minima por tendido, que se debe configurar para los productos.

**Comment by sandramendez** [comment]
se mantiene no deja editar el campo manualmente o deberia estar deshabilitado

**Comment by sandramendez** [comment]
No es error valido con jhon
