### ISSUE TITLE
Ventas y Facturacion -- Generar Factura FD

### ISSUE THREAD

**Issue by jherediab** [fwilchel/gip3#55]
Falta adicionar al reporte PDF el valor en letras.

![image](https://cloud.githubusercontent.com/assets/10456852/8220133/438daeba-1515-11e5-99e9-0d16366c649e.png)

**Comment by d5a9p6s7** [comment]
solucionada en desarrollo. 
es necesario compilar el reporte FacturaDirecta.jrxml pq de lo contrario, los textos se alinearan a la izquierda.
requiere despliegue.

**Comment by sandramendez** [comment]
el campo son esta mostrando null

**Comment by d5a9p6s7** [comment]
solucionada en desarrollo. 
requiere despliegue.

**Comment by sandramendez** [comment]
se genera error al guardar

**Comment by d5a9p6s7** [comment]
Solucionada en desarrollo. 
Requiere despliegue.
