### ISSUE TITLE
comercio nacional-quitar campo de fecha entrega y adicioanr orden compra

### ISSUE THREAD

**Issue by sandramendez** [fwilchel/gip3#59]
Quitar campo Fecha Esperada Entrega del formulario de comercio nacional, dejar  campo con la misma fecha de "Fecha Entrega" en la base de datos

Incluir campo  No. Orden Compra Cliente  no debe ser obligatorio

**Comment by d5a9p6s7** [comment]
Solucionado en desarrollo. 
Requiere despliegue.

**Comment by sandramendez** [comment]
falta Fecha entrega igual a fecha_esperada_entrega

**Comment by d5a9p6s7** [comment]
Solucionado en desarrollo. 
Requiere despliegue.
