### ISSUE TITLE
comercio nacional - ingresar sp - consulta productos por cliente

### ISSUE THREAD

**Issue by d5a9p6s7** [fwilchel/gip3#61]
modificar la consulta para que filtre tambien por los pxc vigentes.

**Comment by d5a9p6s7** [comment]
Solucionado en desarrollo. 
Requiere despliegue.

**Comment by sandramendez** [comment]
al hacer filtro y volver a crear otra solicitud de pedido se  pierde el filtro
![pierdefiltroporcliente](https://cloud.githubusercontent.com/assets/12647386/8380289/8bc4a3e2-1bea-11e5-855f-81a5e0e263d9.png)
