### ISSUE TITLE
auditoria_log -- ERROR: llave duplicada viola restricción de unicidad «log_auditoria_pkey»

### ISSUE THREAD

**Issue by jherediab** [fwilchel/gip3#68]
-- Sequence: auditoria_id_seq

-- DROP SEQUENCE auditoria_id_seq;

CREATE SEQUENCE auditoria_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 561894
  CACHE 1;
ALTER TABLE auditoria_id_seq
  OWNER TO postgres;

select max(id_log) from log_auditoria
561923

**Comment by sandramendez** [comment]
El problema no es la secuencia porque manualmente se soluciono pero jhon necesita que se identifique la causa porlo que se daña ña secuencia

**Comment by sandramendez** [comment]
No se logra replicar
