### ISSUE TITLE
comercio Nacional - Pedidos Nacionales

### ISSUE THREAD

**Issue by d5a9p6s7** [fwilchel/gip3#69]
realizar los siguientes ajustes en la pagina de pedidos nacionales
segun imagen

campos Unidad medida , Sub-Articulos ,  Cantidad Pedida 
Modificar SUBMenu : INGRESAR SOLICITUD COMERCIO NACIONAL POR INGRESAR SOLICITUD 
Modificar Menu: Comercio NAcional por PEDIDOS NACIONALES

![image](https://cloud.githubusercontent.com/assets/1828021/8383809/398e8008-1c02-11e5-9d37-21db701ff321.png)

**Comment by d5a9p6s7** [comment]
se debe correr el script # 46. ...
solucionado en desarrollo 
requiere despliegue

**Comment by sandramendez** [comment]
falta el nombre del menú

**Comment by d5a9p6s7** [comment]
* solucionada en desarrollo
* require ejecutar script 46.
* requiere despliegue
