### ISSUE TITLE
Comercio exterior - Generar Lista de empaque

### ISSUE THREAD

**Issue by jherediab** [fwilchel/gip3#81]
Comercio exterior - Crear Lista de empaque

si esta generando el documento LE, es el mesaje q no muestra el consecutivo de la Lista de Empaque

![image](https://cloud.githubusercontent.com/assets/10456852/8864300/dc55933a-3165-11e5-8c5a-f6563dfc64a9.png)

**Comment by d5a9p6s7** [comment]
* solucionado en desarrollo
* requiere despliegue
