### ISSUE TITLE
Ventas y Facturacion -- Generar Remision Cliente

### ISSUE THREAD

**Issue by jherediab** [fwilchel/gip3#82]
Ventas y Facturacion -- Generar Remision Cliente

error al generar remision. En el documento se detalla el error, si se reintenta de nuevo  el documento Remision se genera satisfactoriamente. en el log genera error con llave duplicada en el tabla de auditoria 

hora 17:34:43

link descarga documentacion de la incidencia
https://www.dropbox.com/s/a4qmxs1y4zvhhl3/incidencia%20Error%20%20generar%20RM.doc?dl=0

log server:
https://www.dropbox.com/s/n0wd7im54hen4gw/server27jul2015.log?dl=0

**Comment by jherediab** [comment]
segunda ocurrencia
https://www.dropbox.com/s/a4qmxs1y4zvhhl3/incidencia%20Error%20%20generar%20RM.doc?dl=0

log server
https://www.dropbox.com/s/jpuos2y15stk5mk/server28JUL2015.log?dl=0

**Comment by jherediab** [comment]
archivo plano para crear remision

https://www.dropbox.com/s/sgg0yjx4ocr6jjh/Gip_RM_VD1-41765-FQ%20STA%20FE%20MDLLIN%20JUL-22_2015jul27_14-01_33.txt?dl=0

**Comment by d5a9p6s7** [comment]
El problema se presenta cuando sobre la misma base de datos se usa la app gip2 y gip3. gip2 al parecer no actualiza la secuencia del log_auditoria, entonces cuando gip3 pide un nuevo valor, este ya existe y genera el error, por eso al volver a ejecutarlo el error no se presenta.
