### ISSUE TITLE
Comercio exterior - Generar Lista de empaque

### ISSUE THREAD

**Issue by jherediab** [fwilchel/gip3#86]
los campos cantidad de estibas , peso bruto estibas y observaciones del documento
habilitar su modificacion y guardar datos al generar LE

adjutno documento
https://www.dropbox.com/s/77bxbu4qrqu88ie/Generar%20LE.doc?dl=0

**Comment by d5a9p6s7** [comment]
* solucionado en desarrollo
* requiere despliegue
