### ISSUE TITLE
Comercio exterior - Asignar datos contribucion cafetera

### ISSUE THREAD

**Issue by jherediab** [fwilchel/gip3#88]
Comercio exterior - Asignar datos contribucion cafetera

adjunto documento con el caso:
Esta borrando los datos cuando se asigna contribución y dex

https://www.dropbox.com/s/8fcdbpryg8gq2hv/Asignacion%20contribucion%20cafetera.doc?dl=0

**Comment by d5a9p6s7** [comment]
* solucionada en desarrollo
* requiere despliegue
