### ISSUE TITLE
Comercio Exterior-Aprobar solicitud de pedido

### ISSUE THREAD

**Issue by sandramendez** [fwilchel/gip3#9]
error al ingresar a la funcionalidad: Message:viewId:/ui/comercioexterior/aprobarSolicitudPedido.jsf - No se pudo restablecer la vista /ui/comercioexterior/aprobarSolicitudPedido.jsf.javax.faces.application.ViewExpiredException: viewId:/ui/comercioexterior/aprobarSolicitudPedido.jsf - No se pudo restablecer la vista /ui/comercioexterior/aprobarSolicitudPedido.jsf.

**Comment by d5a9p6s7** [comment]
Excepción conocida.
ViewExpiredException, No se pudo restablecer la vista. 
Pasa cuando la sesión a expirado.
